/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Diapers' : null } |
  { 'Gear' : null } |
  { 'Toys' : null } |
  { 'Clothing' : null };
export type ExternalBlob = Uint8Array;
export type OrderId = bigint;
export interface OrderInquiry {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'qty' : bigint, 'productId' : ProductId }
export type OrderStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface PlaceOrderInput {
  'customerName' : string,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : ProductId,
  'stockStatus' : StockStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'imageKey' : ExternalBlob,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export type StockStatus = { 'OutOfStock' : null } |
  { 'InStock' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, Category, ExternalBlob, StockStatus],
    Product
  >,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderInquiries' : ActorMethod<[], Array<OrderInquiry>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'placeOrderInquiry' : ActorMethod<[PlaceOrderInput], OrderInquiry>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedSampleProducts' : ActorMethod<[], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, Category, ExternalBlob, StockStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];